<?php

use Illuminate\Database\Seeder;

class Vlan1_listsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $today = date("Y-m-d H:i:s");
        DB::table('vlan1_lists')->insert([
            [
                'vlan1_ipaddr' => '10.30.147.0',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 2,
                'comment' => 'Network Address',
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.1',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.2',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.3',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.4',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.5',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.6',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.7',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.8',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.9',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.10',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.11',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.12',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.13',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.14',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.15',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.16',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.17',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.18',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.19',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.20',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.21',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.22',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.23',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.24',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.25',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.26',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.27',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.28',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.29',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.30',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.31',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.32',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.33',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.34',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.35',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.36',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.37',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.38',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.39',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.40',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.41',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.42',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.43',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.44',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.45',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.46',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.47',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.48',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.49',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.50',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.51',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.52',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.53',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.54',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.55',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.56',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.57',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.58',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.59',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.60',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.61',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.62',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 4,
                'comment' => NULL,
                'updated_at' => $today,
            ],[
                'vlan1_ipaddr' => '10.30.147.63',
                'vm_id' => NULL,
                'vm_name' => NULL,
                'use_flag' => 2,
                'comment' => 'Broadcast Address',
                'updated_at' => $today,
            ],
        ]);
    }
}
